AWSTemplateFormatVersion: '2010-09-09'
Description: 'maestrik

  Notify users SAM Template for maestrik

  '
Globals:
  Function:
    Timeout: 3
Outputs:
  UsersApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/notify-user/
  UsersFunction:
    Description: Users Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UsersFunction
      - Arn
  UsersFunctionIamRole:
    Description: Implicit IAM Role created for users function
    Value:
      Fn::GetAtt:
      - UsersFunctionRole
      - Arn
Resources:
  UsersFunction:
    Properties:
      CodeUri: s3://maestrik/553750cd82abbbfad56f0ceb1608c34d
      Events:
        Users:
          Properties:
            Method: post
            Path: /notify-user
          Type: Api
      Handler: app.lambda_handler
      Runtime: python3.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
